script: 'ci/travis.rb'
before_install:
  - gem install bundler
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
rvm:
  - 1.9.3
env:
  - "GEM=railties"
notifications:
  email: manisha@shippable.com
bundler_args: --path vendor/bundle --without test
services:
  - memcached
