script: 'ci/travis.rb'
before_install:
  - travis_retry gem install bundler
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
rvm:
  - 1.9.3
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,as,av"
  - "GEM=ar:mysql"
  - "GEM=ar:mysql2"
  - "GEM=ar:sqlite3"
  - "GEM=ar:postgresql"
notifications:
  email: manisha@shippable.com
bundler_args: --path vendor/bundle --without test
services:
  - memcached
